In [6]:
# My little btc quote bot

In [122]:
import requests
import json
import numpy as np
import pandas as pd
import time

%matplotlib inline
import matplotlib.pyplot as plt

In [123]:
#baseurl = 'https://blocmarket.herokuapp.com/'
# baseurl = 'http://127.0.0.1:5000/'
baseurl = 'http://127.0.0.1:7000/'

In [266]:
# set up quote api
apikey = 'VVOJSV9CUU9JRCSE'
quoteurl = 'https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=' + apikey
# Test realtime quote 
response = requests.get(quoteurl, headers=headers)
# Look at the quote
response.json()

{'Realtime Currency Exchange Rate': {'1. From_Currency Code': 'BTC',
  '2. From_Currency Name': 'Bitcoin',
  '3. To_Currency Code': 'USD',
  '4. To_Currency Name': 'United States Dollar',
  '5. Exchange Rate': '3647.09000000',
  '6. Last Refreshed': '2019-02-09 23:00:21',
  '7. Time Zone': 'UTC'}}

In [267]:
quote = float(response.json()['Realtime Currency Exchange Rate']['5. Exchange Rate'])
quote

3647.09

In [268]:
# Create a new user
url = baseurl +'createUser'
headers = {'content-type': 'application/json'}
content = {}
response = requests.post(url, data=json.dumps(content), headers=headers)

In [269]:
# View response as json
response.json()

{'signingKey': '8d457749b3d3028a4375c9812b6b2051c545f0c3f2747069b90873b64b8f176a',
 'traderId': '1',
 'verifyKey': '527d39cf001e85321ba9519e57c2e617c122a96182cbbac442c1516b0dae1596'}

In [270]:
# Copy keys and traderid from response
sk = response.json()['signingKey']
vk = response.json()['verifyKey']
tId = int(response.json()['traderId'])

In [271]:
# Create a new market
mkRtId = 1
mkBrId = 1


url = baseurl + 'createMarket'
content_makemarket = {"signingKey": sk,
                        "traderId": tId, 
                        "verifyKey": vk,
                        "marketRootId": mkRtId, 
                        "marketBranchId": mkBrId, 
                        "marketMin": 2500,
                        "marketMax":4500}
# Post market
response = requests.post(url, data=json.dumps(content_makemarket), headers=headers)

In [272]:
# response = requests.post(url, data=json.dumps(content_makemarket), headers=headers)
# View response as json
response.json()

{'allChecks': "{'inputChk': True, 'marketLimitChk': True, 'traderIdChk': True, 'marketId': '1', 'marketRangeChk': True, 'marketIndChk': True, 'sigChk': True, 'chainChk': True, 'ownerChk': True, 'timeChk': True}",
 'checks': 'True',
 'marketBranchId': 1,
 'marketId': 1,
 'marketMax': 4500,
 'marketMin': 2500,
 'marketRootId': 1,
 'traderId': 1}

In [273]:
# Save market id from response
mkId = response.json()['marketId']
quote

3647.09

In [274]:
# Create a trade
tradeurl = baseurl+'createTrade'

content_maketrade = {"signingKey": sk,
                     "traderId": tId,
                     "verifyKey": vk,
                     "marketId": int(mkId),
                     "price":quote,
                     "quantity": 1}
response = requests.post(tradeurl, data=json.dumps(content_maketrade), headers=headers)

In [276]:
# View response as json
response.json()

{'allChecks': "{'inputChk': True, 'traderIdChk': True, 'marketChk': True, 'sigChk': True, 'chainChk': True, 'timeChk': True, 'colChk': True}",
 'checks': 'True',
 'marketId': 1,
 'price': 3647.09,
 'quantity': 1,
 'traderId': 1}

In [1548]:
content_makemarket

{'signingKey': 'b95de2fdcc31bb6bb83f7883f634911efa20a8e9be32595b5c60666fcf08fac2',
 'traderId': 2,
 'verifyKey': 'c888bdd3d2abdf74fd5f22dd6463b916d3ea03b1c3996b897f35312a6ddca562',
 'marketRootId': 2,
 'marketBranchId': 10,
 'marketMin': 0,
 'marketMax': 0.7}

In [ ]:


stillQuoting = True
i=0
while stillQuoting==True:
    # Quote from source
    i+=1
    response = requests.get(quoteurl, headers=headers)
    quote = float(response.json()['Realtime Currency Exchange Rate']['5. Exchange Rate'])
    # Make a bid
    content_maketrade['price'] = quote-1
    content_maketrade['quantity'] =1
    response = requests.post(tradeurl, data=json.dumps(content_maketrade), headers=headers)
    # Make an offer
    content_maketrade['price'] = quote+1
    content_maketrade['quantity'] = -1
    response = requests.post(tradeurl, data=json.dumps(content_maketrade), headers=headers)
    time.sleep(3*60)
    
    # Remove bid 
    content_maketrade['price'] = quote-1
    content_maketrade['quantity'] =-1
    response = requests.post(tradeurl, data=json.dumps(content_maketrade), headers=headers)
    # Remove offer
    content_maketrade['price'] = quote+1
    content_maketrade['quantity'] = 1
    response = requests.post(tradeurl, data=json.dumps(content_maketrade), headers=headers)
    print('Price for iteration ' + str(i) + ' : ' + str(content_maketrade['price']))

Price for iteration 1 : 3648.31
Price for iteration 2 : 3647.45
Price for iteration 3 : 3648.88
Price for iteration 4 : 3649.23
Price for iteration 5 : 3645.42
Price for iteration 6 : 3645.45
Price for iteration 7 : 3645.96
Price for iteration 8 : 3646.43
Price for iteration 9 : 3646.43
Price for iteration 10 : 3646.71
Price for iteration 11 : 3645.72
Price for iteration 12 : 3647.95
Price for iteration 13 : 3648.16
Price for iteration 14 : 3649.11
Price for iteration 15 : 3650.56
Price for iteration 16 : 3652.77
Price for iteration 17 : 3651.49
Price for iteration 18 : 3650.15
Price for iteration 19 : 3651.87
Price for iteration 20 : 3653.09
Price for iteration 21 : 3654.16
Price for iteration 22 : 3653.27
Price for iteration 23 : 3655.63
Price for iteration 24 : 3655.86
Price for iteration 25 : 3657.99
Price for iteration 26 : 3657.54
Price for iteration 27 : 3658.77
Price for iteration 28 : 3656.92
Price for iteration 29 : 3658.78
Price for iteration 30 : 3658.93
Price for iteration 31 : 3658.94
Price for iteration 32 : 3657.91
Price for iteration 33 : 3657.26
Price for iteration 34 : 3653.02
Price for iteration 35 : 3653.9
Price for iteration 36 : 3654.97
Price for iteration 37 : 3653.79
Price for iteration 38 : 3653.18
Price for iteration 39 : 3645.67
Price for iteration 40 : 3646.13
Price for iteration 41 : 3646.47
Price for iteration 42 : 3645.84
Price for iteration 43 : 3645.98
Price for iteration 44 : 3646.13
Price for iteration 45 : 3643.91
Price for iteration 46 : 3644.71
Price for iteration 47 : 3644.93
Price for iteration 48 : 3644.95
Price for iteration 49 : 3646.87
Price for iteration 50 : 3646.86
Price for iteration 51 : 3644.01
Price for iteration 52 : 3645.19
Price for iteration 53 : 3647.18
Price for iteration 54 : 3648.18
Price for iteration 55 : 3649.22
Price for iteration 56 : 3645.91
Price for iteration 57 : 3646.8
Price for iteration 58 : 3647.18
Price for iteration 59 : 3647.07
Price for iteration 60 : 3647.32
Price for iteration 61 : 3649.49
Price for iteration 62 : 3647.26
Price for iteration 63 : 3648.61
Price for iteration 64 : 3649.1
Price for iteration 65 : 3649.88
Price for iteration 66 : 3650.43
Price for iteration 67 : 3650.55
Price for iteration 68 : 3649.1
Price for iteration 69 : 3649.01
Price for iteration 70 : 3649.86
Price for iteration 71 : 3649.29
Price for iteration 72 : 3649.97
Price for iteration 73 : 3646.02
Price for iteration 74 : 3646.28
Price for iteration 75 : 3646.96
Price for iteration 76 : 3648.8
Price for iteration 77 : 3648.84
Price for iteration 78 : 3649.7
Price for iteration 79 : 3647.01
Price for iteration 80 : 3647.07
Price for iteration 81 : 3647.07
Price for iteration 82 : 3648.37
Price for iteration 83 : 3647.27
Price for iteration 84 : 3648.31
Price for iteration 85 : 3647.88
Price for iteration 86 : 3648.61
Price for iteration 87 : 3649.14
Price for iteration 88 : 3649.07
Price for iteration 89 : 3650.24
Price for iteration 90 : 3647.16
Price for iteration 91 : 3647.8
Price for iteration 92 : 3647.17
Price for iteration 93 : 3647.07
Price for iteration 94 : 3646.92
Price for iteration 95 : 3648.1
Price for iteration 96 : 3647.0
Price for iteration 97 : 3647.69
Price for iteration 98 : 3647.44
Price for iteration 99 : 3647.37
Price for iteration 100 : 3648.72
Price for iteration 101 : 3644.7
Price for iteration 102 : 3645.29
Price for iteration 103 : 3646.33
Price for iteration 104 : 3646.69
Price for iteration 105 : 3647.48
Price for iteration 106 : 3647.98
Price for iteration 107 : 3646.22
Price for iteration 108 : 3646.41
Price for iteration 109 : 3646.19
Price for iteration 110 : 3646.84
Price for iteration 111 : 3647.54
Price for iteration 112 : 3648.66
Price for iteration 113 : 3648.77
Price for iteration 114 : 3650.63
Price for iteration 115 : 3650.04
Price for iteration 116 : 3650.93
Price for iteration 117 : 3651.91
Price for iteration 118 : 3649.2
Price for iteration 119 : 3648.0
Price for iteration 120 : 3649.63
Price for iteration 121 : 3649.81
Price for iteration 122 : 3647.48
Price for iteration 123 : 3648.23
Price for iteration 124 : 3645.8
Price for iteration 125 : 3646.88
Price for iteration 126 : 3647.43
Price for iteration 127 : 3648.84
Price for iteration 128 : 3648.35
Price for iteration 129 : 3648.34
Price for iteration 130 : 3646.71
Price for iteration 131 : 3646.73
Price for iteration 132 : 3646.41
Price for iteration 133 : 3647.44
Price for iteration 134 : 3647.99
Price for iteration 135 : 3645.49
Price for iteration 136 : 3646.4

In [162]:
content_maketrade

{'signingKey': '7f483db2a4d837caf55d7b5b5d5b8923faa1a21802f817bfe00b07aa13187bef',
 'traderId': 1,
 'verifyKey': '2985c55dde343a6f024867acca6b64263f171aa5e5b1ee65620b1763b86fd37e',
 'marketId': 1,
 'price': 3625.7,
 'quantity': -1}

In [199]:
content_maketrade['quantity'] = quote

In [200]:
response = requests.post(tradeurl, data=json.dumps(content_maketrade), headers=headers)

In [201]:
response.json()

{'allChecks': "{'inputChk': True, 'traderIdChk': True, 'marketChk': True, 'sigChk': True, 'chainChk': True, 'timeChk': True, 'colChk': True}",
 'checks': 'True',
 'marketId': 1,
 'price': 3625.7,
 'quantity': 2.0,
 'traderId': 1}

'http://127.0.0.1:7000/createTrade'

In [197]:
# View summary of trader for a particular trader
url = baseurl+'viewTradeSummary'
content = {'traderId': int(tId)}
response = requests.post(url, data=json.dumps(content), headers=headers, stream=True)

In [198]:
pd.read_json(response.json())

,marketId,price,quantity,traderId,iMatched,timeStampUTC,marketRootId,marketBranchId,marketMin,marketMax,marketMinOutcome,marketMaxOutcome
0,1,0.50,1,1,False,2019-02-09 07:42:46.453,1,1,2500,4500,2499.50,4499.50
1,1,3654.85,-1,1,False,2019-02-09 07:45:23.233,1,1,2500,4500,1154.85,-845.15
10,1,3654.42,-1,1,False,2019-02-09 07:46:27.127,1,1,2500,4500,1154.42,-845.58
11,1,3652.42,-1,1,False,2019-02-09 07:49:27.231,1,1,2500,4500,1152.42,-847.58
12,1,3649.60,-1,1,False,2019-02-09 07:49:29.240,1,1,2500,4500,1149.60,-850.40
13,1,3647.60,-1,1,False,2019-02-09 07:52:29.344,1,1,2500,4500,1147.60,-852.40
14,1,3652.97,-1,1,False,2019-02-09 07:52:31.267,1,1,2500,4500,1152.97,-847.03
15,1,3650.97,-1,1,False,2019-02-09 07:55:31.372,1,1,2500,4500,1150.97,-849.03
16,1,3648.03,-1,1,False,2019-02-09 07:55:33.366,1,1,2500,4500,1148.03,-851.97
17,1,3646.03,-1,1,False,2019-02-09 07:58:33.471,1,1,2500,4500,1146.03,-853.97
18,1,3648.76,-1,1,False,2019-02-09 07:58:35.702,1,1,2500,4500,1148.76,-851.24
19,1,3646.76,-1,1,False,2019-02-09 08:01:35.799,1,1,2500,4500,1146.76,-853.24
2,1,3652.85,-1,1,False,2019-02-09 07:45:26.333,1,1,2500,4500,1152.85,-847.15
20,1,3641.76,-1,1,False,2019-02-09 08:01:38.472,1,1,2500,4500,1141.76,-858.24
21,1,3639.76,-1,1,False,2019-02-09 08:04:38.580,1,1,2500,4500,1139.76,-860.24
22,1,3635.70,-1,1,False,2019-02-09 08:04:40.340,1,1,2500,4500,1135.70,-864.30
23,1,3633.70,-1,1,False,2019-02-09 08:07:40.445,1,1,2500,4500,1133.70,-866.30
24,1,3634.78,-1,1,False,2019-02-09 08:07:42.309,1,1,2500,4500,1134.78,-865.22
25,1,3632.78,-1,1,False,2019-02-09 08:10:42.425,1,1,2500,4500,1132.78,-867.22
26,1,3633.01,-1,1,False,2019-02-09 08:10:44.444,1,1,2500,4500,1133.01,-866.99
27,1,3631.01,-1,1,False,2019-02-09 08:13:44.549,1,1,2500,4500,1131.01,-868.99
28,1,3636.28,-1,1,False,2019-02-09 08:13:46.388,1,1,2500,4500,1136.28,-863.72
29,1,3634.28,-1,1,False,2019-02-09 08:16:46.482,1,1,2500,4500,1134.28,-865.72
3,1,3654.24,-1,1,False,2019-02-09 07:45:53.582,1,1,2500,4500,1154.24,-845.76
30,1,3636.88,-1,1,False,2019-02-09 08:16:51.892,1,1,2500,4500,1136.88,-863.12
31,1,3634.88,-1,1,False,2019-02-09 08:19:51.999,1,1,2500,4500,1134.88,-865.12
32,1,3631.86,-1,1,False,2019-02-09 08:19:53.901,1,1,2500,4500,1131.86,-868.14
33,1,3629.86,-1,1,False,2019-02-09 08:22:54.009,1,1,2500,4500,1129.86,-870.14
34,1,3631.04,-1,1,False,2019-02-09 08:22:55.796,1,1,2500,4500,1131.04,-868.96
35,1,3629.04,-1,1,False,2019-02-09 08:25:55.907,1,1,2500,4500,1129.04,-870.96
...,...,...,...,...,...,...,...,...,...,...,...,...
71,1,3620.37,-1,1,False,2019-02-09 09:20:33.814,1,1,2500,4500,1120.37,-879.63
72,1,3627.42,-1,1,False,2019-02-09 09:20:35.633,1,1,2500,4500,1127.42,-872.58
73,1,3625.42,-1,1,False,2019-02-09 09:23:35.753,1,1,2500,4500,1125.42,-874.58
74,1,3626.39,-1,1,False,2019-02-09 09:23:37.663,1,1,2500,4500,1126.39,-873.61
75,1,3624.39,-1,1,False,2019-02-09 09:26:37.776,1,1,2500,4500,1124.39,-875.61
76,1,3626.30,-1,1,False,2019-02-09 09:26:39.616,1,1,2500,4500,1126.30,-873.70
77,1,3624.30,-1,1,False,2019-02-09 09:29:39.735,1,1,2500,4500,1124.30,-875.70
78,1,3626.25,-1,1,False,2019-02-09 09:29:41.516,1,1,2500,4500,1126.25,-873.75
79,1,3624.25,-1,1,False,2019-02-09 09:32:41.623,1,1,2500,4500,1124.25,-875.75
8,1,3652.24,-1,1,False,2019-02-09 07:46:06.302,1,1,2500,4500,1152.24,-847.76
80,1,3628.09,-1,1,False,2019-02-09 09:32:43.623,1,1,2500,4500,1128.09,-871.91
81,1,3626.09,-1,1,False,2019-02-09 09:35:43.741,1,1,2500,4500,1126.09,-873.91
82,1,3626.94,-1,1,False,2019-02-09 09:35:45.810,1,1,2500,4500,1126.94,-873.06
83,1,3624.94,-1,1,False,2019-02-09 09:38:45.930,1,1,2500,4500,1124.94,-875.06
84,1,3628.62,-1,1,False,2019-02-09 09:39:34.968,1,1,2500,4500,1128.62,-871.38
85,1,3626.62,-1,1,False,2019-02-09 09:42:35.078,1,1,2500,4500,1126.62,-873.38
86,1,3628.98,-1,1,False,2019-02-09 09:42:37.655,1,1,2500,4500,1128.98,-871.02
87,1,3626.98,-1,1,False,2019-02-09 09:45:37.765,1,1,2500,4500,1126.98,-873.02
88,1,3628.58,-1,1,False,2019-02-09 09:45:39.998,1,1,2500,4500,1128.58,-871.42
89,1,3626.58,-1,1,False,2019-02-09 09:48:40.107,1,1,2500,4500,1126.58,-873.42
9,1,3654.25,-1,1,False,2019-02-09 07:46:08.033,1,1,2500,4500,1154.25,-845.75
90,1,3627.24,-1,1,False,2019-02-09 09:48:43.369,1,1,2500,4500,1127.24,-872.76
91,1,3625.24,-1,1,False,2019-02-09 09:51:43.480,1,1,2500,4500,1125.24,-874.76
92,1,3625.70,-1,1,False,2019-02-09 09:58:39.423,1,1,2500,4500,1125.70,-874.30
93,1,3625.70,-1,1,False,2019-02-09 09:59:12.688,1,1,2500,4500,1125.70,-874.30
94,1,3625.70,-2,1,False,2019-02-09 10:00:44.921,1,1,2500,4500,2251.40,-1748.60
95,1,3625.70,-1,1,False,2019-02-09 10:07:34.405,1,1,2500,4500,1125.70,-874.30
96,1,3625.70,1,1,False,2019-02-09 10:10:49.292,1,1,2500,4500,-1125.70,874.30
97,1,3625.70,-1,1,True,2019-02-09 09:51:45.887,1,1,2500,4500,1125.70,-874.30
98,1,3625.70,1,1,True,2019-02-09 10:10:49.292,1,1,2500,4500,-1125.70,874.30